const config = {
    BASEURL: String(import.meta.env.VITE_API_URL),
    signInLink: "auth/login/",
    signUpLink: "auth/sendemailLINK/",
    verificationCheckerLink: "auth/verifyemailLINK/",
    sendEmailOtpLink: "auth/sendemailOTP/",
    verifyEmailOtpLink: "auth/verifyemailOTP/",
    resetPassLink: "auth/resetpassword/",
    renewTokenLink: "auth/token/",
    loginTwoFactorVerify: "auth/twofactor/",
    panLink: "profile/verifyPAN/",
    userDetails: "profile/details",
    changePasswordLink: "profile/changepassword/",
    updateProfilePhoto: "profile/profile_picture/",
    newTwoFactor: "profile/newtwofactor/",
    verifyTwoFactor: "profile/verifytwofactor/",
    enableTwoFactor: "profile/enabletwofactor/",
    disableTwoFactor: "profile/disabletwofactor/",
    newsLink: "invest/news/",
    holdingApiLink: "invest/myholdings/",
    inWatchlist: "invest/inwatchlist/?coin=",
    modifyWatchlist: "invest/mywatchlist/",
    coinDetailsLink: "invest/coindetails/?coin=",
    transactionLink: "invest/transactions/",
    buyCoinLink: "invest/buy/",
    sellCoinLink: "invest/sell/",
}

export default config