name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: echo VITE_BASE_URL="${{ secrets.VITE_BASE_URL }}" > .env && echo VITE_BASE_URL_WS="${{ secrets.VITE_BASE_URL_WS }}" >> .env

      - name: Build Project
        run: npm run build

      - name: Copy Files to EC2
        run: sshpass -p ${{ secrets.EC2_PASSWORD }} scp -o StrictHostKeyChecking=no -r dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:cryptbee/

      - name: SSH into EC2 and Stop Previous HTTP Server
        run: sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'
